### post request

POST  http://localhost:5001/register/
Content-Type: application/json

{
  "username": "Pon",
  "password": "123456"
}

###
POST  http://localhost:5001/user/login/
Content-Type: application/json

{
  "username": "sakthi",
  "password": "123456"
}
###

GET http://localhost:5001/user/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNha3RoaSIsImlhdCI6MTcyMjYwMjMwNH0.mGU1wDdxzfcJKJcjrq1plra02O7OvrySFTxuzoLXmrw


###
POST http://localhost:5001/admin/admin-login/
Content-Type: application/json

{
  "adminname": "nato",
  "password": "1234567890"
}




